### ISSUE TITLE
where is the storage folder for the image? the web won't load the image

### ISSUE THREAD

**Issue by mujibluth** [Prajwal100/Advance-Ecommerce-in-laravel-7#34]
![image](https://user-images.githubusercontent.com/67505650/122615614-fd752100-d0b2-11eb-9561-d711760ff5f4.png)
where can i find the image assets? so the web can load existing images gambar

**Comment by Xyl1an** [comment]
same

**Comment by Yusufalfi** [comment]
same

**Comment by Prajwal100** [comment]
@mujibluth I uploaded storage.zip in the root level. Extract that folder and replace the root level storage folder.
