### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by godwinwaswa** [Prajwal100/Advance-Ecommerce-in-laravel-7#37]
I cloned the repo to my machine but I'm running on php 8 which installed automatically by running the command on my Linux terminal,I don't know if this project can be run by php 8.If yes how can I do that.And if it's php 7,how can I install php7 on my linux machine.Thanks,waiting,this project is so cool and I'd like to run it today

**Comment by Prajwal100** [comment]
Please check other tutorials to install PHP 7.
