### ISSUE TITLE
File Manager bug

### ISSUE THREAD

**Issue by jechaviz** [Prajwal100/Advance-Ecommerce-in-laravel-7#38]
I'm running the app at my local, and all goes ok, except file-manager.
I have reviewed the code and in 
Advance-Ecommerce-in-laravel-7\config\lfm.php

is missing this in all places
'image/jpg',

Also the preview link it's generated with localhost, not with localhost:8000. I assured myself to have in .env 
APP_URL=http://localhost:8000

So that's not the problem. The images are look like stored, but the public/storage folder isn't modified at all, but the images are listed. but the thumbnails aren't visible.

I have looked up in https://unisharp.github.io/laravel-filemanager/ documentation
And I have installed the PHP extensions required.
I'm running with PHP 8, but it hasn't raised any exception, just doesn't show the images

![image](https://user-images.githubusercontent.com/6210208/125899352-5086e15c-6342-451d-bbaf-27f34452a9b6.png)

One thing more, I ran composer update after cloning the repo, without issues.

Thank you in advance for your support

**Comment by Prajwal100** [comment]
@jechaviz Thank you
