### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by dean-su** [Prajwal100/Advance-Ecommerce-in-laravel-7#39]
Hello,

After set up the website, there was no any images showing.
Can you please upload the images at \storage\app\public , thanks!

**Comment by mubixh** [comment]
Hy
Please extract the public folder which is placed in main directory, and put folders that are in public folder to the path 
/public/storage/ 
All images will be correct.
But there is still problem when we uploaded a new image from local pc its not showing that image

**Comment by yashajay17** [comment]
Please Provide Image Folder on Gihub

**Comment by Prajwal100** [comment]
@mubixh pls first run "php artisan storage:link" then it will create a storage folder under public. After that, paste the image folder.

**Comment by yashajay17** [comment]
Thanks ☺️ it Worked
