### ISSUE TITLE
Image not show when upload on File Manager

### ISSUE THREAD

**Issue by soknatchan** [Prajwal100/Advance-Ecommerce-in-laravel-7#4]
![filemanager](https://user-images.githubusercontent.com/24784118/96103259-b02c2880-0f01-11eb-8266-ba0e8d487719.PNG)

When I upload images on file manager, it's not show the images.

**Comment by dianajoan** [comment]
Yes i have been receiving the same problem as well.

And when i try to do this:

**cd public
rm storage
php artisan storage:link**

it works for a short while as i upload images, then later doesn't show images.

**Comment by ShineBetter** [comment]
i think my file manager has error i wanna to correct this

**Comment by sergijPf** [comment]
You could resolve it by copying **/resources/template/photo** folder to **/storage/app/public/**

**Comment by ayoubkhan558** [comment]
> i think my file manager has error i wanna to correct this

Can you please use the any alternative to File Manager, Because it does not look professional .

**Comment by kevokyforce** [comment]
Mine to is not working after copying photo from resources to public

**Comment by a6e6s** [comment]
Just remove the old link and create new link and it will work perfectly 
"Just delet the public/storage file and run php artisan storage:link"

**Comment by xetryDcoder** [comment]
Can anybody elaborate the  solution for this?

**Comment by xetryDcoder** [comment]
Actually this can be solved by editing the .env file.
Where you can add ':8000' to http://localhost
which looks like 
 APP_URL=http://localhost:8000

**Comment by thilaju** [comment]
> You could resolve it by copying **/resources/template/photo** folder to **/storage/app/public/**

I added photos folder to public, but no changes. Do we need to rename the folder?

**Comment by Hakkey** [comment]
1. Go to public folder and delete the existing "storage" folder (if there is any)
2. Run _php artisan storage:link_ in terminal
3. Problem solved
4. Continue to code until u find another problem

**Comment by OswalDev** [comment]
> 1. Go to public folder and delete the existing "storage" folder (if there is any)
> 2. Run _php artisan storage:link_ in terminal
> 3. Problem solved
> 4. Continue to code until u find another problem

This solved my problem, thank you!

**Comment by thilaju** [comment]
I am in the progress of reconfiguring
do we need to php artisan storage:link in the laravel file manager
where do we do that?

**Comment by thilaju** [comment]
> You could resolve it by copying **/resources/template/photo** folder to **/storage/app/public/**

this worked perfectly
make sure php artisan serve after the change

**Comment by AddeNanda** [comment]
> 1. Go to public folder and delete the existing "storage" folder (if there is any)
> 2. Run _php artisan storage:link_ in terminal
> 3. Problem solved
> 4. Continue to code until u find another problem

this also solve mine, thanks

**Comment by Elegance002** [comment]
Photo upload choose button doesn't work on cpanel. Why????

**Comment by Rosso2050** [comment]
> 1. Go to public folder and delete the existing "storage" folder (if there is any)
> 2. Run _php artisan storage:link_ in terminal
> 3. Problem solved
> 4. Continue to code until u find another problem

Perfect

**Comment by Prajwal100** [comment]
> 1. Go to public folder and delete the existing "storage" folder (if there is any)
> 2. Run _php artisan storage:link_ in terminal
> 3. Problem solved
> 4. Continue to code until u find another problem

Thank you @Hakkey
