### ISSUE TITLE
folder missing

### ISSUE THREAD

**Issue by DesixMimi** [Prajwal100/Advance-Ecommerce-in-laravel-7#48]
The folder "/Advance-Ecommerce-in-laravel-7-master/storage/app/public" containing all the images, which was presented in the video tutorial is missing.

**Comment by thayronarrais** [comment]
Hi, this folder has been zipped in the root folder, the name is public.zip.

**Comment by DesixMimi** [comment]
> Hi, this folder has been zipped in the root folder, the name is public.zip. I hope it helps

I saw it now, thank you very much for the help and the quick response!

**Comment by Prajwal100** [comment]
Thank you @thayronarrais

**Comment by Prajwal100** [comment]
Thank you @thayronarrais
