### ISSUE TITLE
File browser broken

### ISSUE THREAD

**Issue by sly04** [Prajwal100/Advance-Ecommerce-in-laravel-7#57]
Hello. I've tried and installed this wonderful platform. But  I can't upload a file in the admin section because when I clicked on the button 'photo', nothing occurs. I've tried to add a new product. The situation is similar when I try to add a new banner and so on.

**Comment by Prajwal100** [comment]
@sly04 please, explore this package https://unisharp.github.io/laravel-filemanager/installation

**Comment by RAZ321** [comment]
hi can you send the screen capture pls

**Comment by dzeusif** [comment]
Did anyone get a fix to this issue, Im facing the same issue

**Comment by Prajwal100** [comment]
@dzeusif please pull the lastest code.
![image](https://github.com/Prajwal100/Advance-Ecommerce-in-laravel-7/assets/29488275/69b8dbca-422e-4ac8-9c68-461faafbaf56)
