### ISSUE TITLE
Image loding

### ISSUE THREAD

**Issue by Orochimaru97** [Prajwal100/Advance-Ecommerce-in-laravel-7#63]
Hi, i can't load images .
![ecommerce](https://user-images.githubusercontent.com/93274934/166299391-235ae17d-9237-42fe-b317-4acb6ed05cea.png)

**Comment by RAZ321** [comment]
Yes because there isn't pictures in Advance-Ecommerce-in-laravel-7\storage\app\photos

**Comment by RAZ321** [comment]
he forgot to upload the folder

**Comment by Orochimaru97** [comment]
Thanks work fine.
