### ISSUE TITLE
file manager is not working

### ISSUE THREAD

**Issue by malekkadri** [Prajwal100/Advance-Ecommerce-in-laravel-7#82]
![image](https://user-images.githubusercontent.com/93520204/205752596-84e09b2c-c1d4-4fca-8863-4e10c0a0a8c8.png)
![image](https://user-images.githubusercontent.com/93520204/205752650-28eac7af-60f4-4dbc-8ea2-dec2417d9e5a.png)
I tried to re-install the package and nothing changed :( help please!

**Comment by shubham9098** [comment]
first you go to you Application and go back to public folder and then remove storage file 
then run command php artisan storage:link 
then solve your problem

**Comment by malekkadri** [comment]
thank you !

**Comment by dkklimo** [comment]
I have the same issue as the images above, I have removed storage folder and then run command php artisan storage:link but it just created the folder storage/files/1 in public folder with no images.

**Comment by senuradp** [comment]
even i have the same issue, i did remove the storage file and tried but I still have the same issue.

**Comment by Prajwal100** [comment]
@dkklimo Fixed this issue please pull latest code. 
https://github.com/Prajwal100/Advance-Ecommerce-in-laravel-7/issues/57
