### ISSUE TITLE
I already uploaded image for product and other stuff, but not displaying

### ISSUE THREAD

**Issue by fadhiladz** [Prajwal100/Advance-Ecommerce-in-laravel-7#94]
Hi, i already installed everything. Tried to create new product and uploading the image. The upload is completed but the image is not displaying. Is there any step missed? I already run php artisan storage:link

**Comment by kingispeak** [comment]
Try remove public storage folder and run ```php artisan storage:link```

**Comment by Prajwal100** [comment]
@fadhiladz pull the latest code and try it 
![image](https://github.com/Prajwal100/Advance-Ecommerce-in-laravel-7/assets/29488275/8564844c-661f-4ca3-b931-3d3560ef00b0)
